-- Optional observations recorded by Taller when its work is completed.
-- The server still assigns this identity automatically. BY DEFAULT permits the
-- controlled, transactional renumbering performed only by the admin DELETE endpoint.
ALTER TABLE orders
  ALTER COLUMN number SET GENERATED BY DEFAULT;

ALTER TABLE order_activities
  ADD COLUMN IF NOT EXISTS workshop_notes text
  CHECK (workshop_notes IS NULL OR length(workshop_notes) <= 4000);

-- Legacy, non-composite Taller flow keeps the same information on the parent OT.
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS workshop_notes text
  CHECK (workshop_notes IS NULL OR length(workshop_notes) <= 4000);
